main: me.alientation.customgui.CustomGUIPlugin
name: CustomGUI
version: '0.0.0'
description: A simple and easy to use GUI API
author: Alientation
permissions:
  customgui:
    description: Allows CustomGUI Commands
    default: op